src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(fields={"title"}, message="Ce titre existe déjà")
 */
class Property
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rating", mappedBy="property")
     */
    private $ratings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="property")
     */
    private $bookings;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="property")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Location", mappedBy="property")
     */
    private $locations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sell", mappedBy="property")
     */
    private $sells;

    public function __construct()
    {
        $this->ratings = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->locations = new ArrayCollection();
        $this->sells = new ArrayCollection();
    }

    /**
     * @return \DateTime
     * @throws \Exception
     * @ORM\PrePersist()
     */
    public function createdFunction()
    {
        return $this->createdAt = new \DateTime();
    }
    /**
     * @param User $user
     * @return null
     */
    public function ratingUser(User $user)
    {
        foreach($this->ratings as $rating){
            if($rating->getAuthor() === $user){
                return $rating;
            }
        }
        return null;
    }

    /**
     * @return float|int
     */
    public function getAvgRatings()
    {
        // calcul de la somme des notation
        $sum = array_reduce($this->ratings->toArray(), function($total, $note){
            return $total + $note->getRating();
        },0);

        // moyenne des notation
        if(count($this->ratings) > 0) return $sum / count($this->ratings);

        return 0;
    }

    /**
     * @return array
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];
        foreach ($this->bookings as $booking){
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function ($dayTimestamp){
                return new  \DateTime(date('Y-m-d', $dayTimestamp));
            },$resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setProperty($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getProperty() === $this) {
                $rating->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setProperty($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getProperty() === $this) {
                $booking->setProperty(null);
            }
        }

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setProperty($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getProperty() === $this) {
                $location->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Sell[]
     */
    public function getSells(): Collection
    {
        return $this->sells;
    }

    public function addSell(Sell $sell): self
    {
        if (!$this->sells->contains($sell)) {
            $this->sells[] = $sell;
            $sell->setProperty($this);
        }

        return $this;
    }

    public function removeSell(Sell $sell): self
    {
        if ($this->sells->contains($sell)) {
            $this->sells->removeElement($sell);
            // set the owning side to null (unless already changed)
            if ($sell->getProperty() === $this) {
                $sell->setProperty(null);
            }
        }

        return $this;
    }

}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\Rating;
use App\Form\RatingType;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("")
 */
class PropertyController extends AbstractController
{
    /**
     * @Route("/property", name="property_index", methods={"GET"})
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        return $this->render('property/index.html.twig', [
            'properties' => $propertyRepository->findAll(),
        ]);
    }

    /**
 * @Route("/property/{id}", name="property_show", methods={"GET", "POST"})
 */
    public function show(Property $property, Request $request): Response
    {
        $rating = new Rating();
        $form = $this->createForm(RatingType::class, $rating);
        $form->handleRequest($request);
        if($form->isSubmitted() and $form->isValid()){
            $rating->setProperty($property)
                ->setAuthor($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rating);
            $entityManager->flush();

        }
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'form' => $form->createView()
        ]);
    }
}

src/Controller/admin/PropertyController.php
<?php
namespace App\Controller\admin;

use App\Entity\Property;
use App\Form\PropertyType;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PropertyController
 * @package App\Controller\admin
 * @Route("/admin", name="admin_")
 */
class PropertyController extends AbstractController
{

    /**
     * @Route("/property", name="property_index", methods={"GET"})
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        return $this->render('admin/property/index.html.twig', [
            'properties' => $propertyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/property/new", name="property_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form['image']->getData();
            $name = md5(uniqid()).'.'.$image->guessExtension();
            $image->move(
                $this->getParameter('image_property_directory'),
                $name
            );
            $property->setImage($image);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($property);
            $entityManager->flush();

            return $this->redirectToRoute('admin_property_show', ['id' => $property->getId()]);
        }

        return $this->render('admin/property/new.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/property/{id}", name="property_show", methods={"GET", "POST"})
     */
    public function show(Property $property): Response
    {
        return $this->render('admin/property/show.html.twig', [
            'property' => $property,
        ]);
    }
    /**
     * @Route("/property/{id}/edit", name="property_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Property $property): Response
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form['image']->getData();


            $name = md5(uniqid()).'.'.$image->guessExtension();
            $image->move(
                $this->getParameter('image_property_directory'),
                $name
            );

            $property->setImage($name);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_property_show', ['id' => $property->getId()]);
        }

        return $this->render('admin/property/edit.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/property/{id}", name="property_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Property $property): Response
    {
        if ($this->isCsrfTokenValid('delete'.$property->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($property);
            $entityManager->flush();
        }

        return $this->redirectToRoute('property_index');
    }

}

templates/property/_property.html.twig
{% set url = path('property_show', { 'id': property.id }) %}
<div class="single-portfolio col-md-4">
    <div class="inner">
        <div class="portfolio-content">
            <dl>
                <dt>Type : {{ property.type.name }} </dt>
                <dt>Status de la Propriété :
                    <strong>
                        {% if property.type.name == "vente" %}
                            {{ property.sold ? 'Acheter' : 'Toujour disponible' }}
                        {% else %}
                            {{ property.sold ? 'Loué' : 'Toujour disponible' }}
                        {% endif %}
                    </strong>
                </dt>
            </dl>
            {% if property.ratings|length > 0 %}
                {{ include('partials/_rating.html.twig' , {'rating': property.avgRatings}) }}<br>
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <div class="portfolio-img">
            <img height="200" src="{{ asset('assets/img/page-title.jpg') }}" alt="portfolio-image">
            <div class="hover-content">
                <div>
                    <a href="{{ url }}" class="button">plus d'information</a>
                </div>
            </div>
        </div>
        <div class="portfolio-content">
            <a href="{{ url }}"><h3>{{ property.title }}</h3></a>
            <span>Prix : {{ property.price|number_format(2, ',', ' ') }} Fcfa </span>
            <span> Surface : {{ property.surface }} m²</span>
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous nos propriétés{% endblock %}

{% block body %}
    <div class="page-title sp" style="background-image: url({{ asset('assets/img/page-title.jpg') }})">
        <div class="container text-center">
            <h2>Nos Propriété </h2>
            <p>Malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>
        </div>
    </div>
    <div class="portfolio-area sp">
        <div class="container">
            <div class="row">
                {% for property in properties %}
                    {{ include('property/_property.html.twig') }}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propriété : {{ property.title }}{% endblock %}

{% block body %}
    <div class="page-title sp" style="background-image: url({{ asset('assets/img/page-title.jpg') }})">
        <div class="container text-center">
            <h2>Propriété : {{ property.title }}</h2>
        </div>
    </div>
    <div class="about-area sp">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="about-content">
                        <h3>Desciption de la propriété </h3>
                        <p> {{ property.description | raw }}</p>
                        <dl>
                            <dt>
                                {% if property.type.name == "vente" %}
                                    <p>Prix de vente : <strong>{{ property.price|number_format(2, ',', ' ') }} fcfa</strong></p>
                                {% else %}
                                    <p>Prix de location : <strong>{{ property.price|number_format(2, ',', ' ') }} fcfa</strong> / mois</p>
                                {% endif %}
                            </dt>
                            <dt>Status de la Propriété :
                                <strong>
                                    {% if property.type.name == "vente" %}
                                        {{ property.sold ? 'Acheter' : 'Toujour disponible' }}
                                    {% else %}
                                        {{ property.sold ? 'Loué' : 'Toujour disponible' }}
                                    {% endif %}
                                </strong>
                            </dt>
                        </dl>

                        {% if app.user %}
                            {% set note = property.ratingUser(app.user) %}

                            {% if note is not null %}
                                <dl class="row align-items-center" style="margin-top: 1.5em;">
                                    <dt class="h4 col-sm-3">Votre note :</dt>
                                    <dd class="col-sm-6 " style="color: goldenrod">{{ include('partials/_rating.html.twig' , {'rating': note.rating}) }}</dd>
                                </dl>
                            {% else %}
                                {{ form_start(form) }}
                                {{ form_row(form.rating) }}
                                <button class="button-2">Noté!</button>
                                {{ form_end(form) }}
                            {% endif %}
                        {% else %}
                            {{ include('partials/_rating.html.twig' , {'rating': property.avgRatings}) }}<br>
                        {% endif %}

                        {% if property.sold == false %}
                            {% if property.type.name == "vente" %}
                                <a href="{{ path('property_booking_new', {'id': property.id}) }}" class="button">Réserver pour vente</a>
                            {% else %}
                                <a href="{{ path('property_booking_new', {'id': property.id}) }}" class="button">Réserver pour location</a>
                            {% endif %}
                        {% else %}
                            {% if property.type.name == "vente" %}
                                <strong>Cette propriété ne peut-etre vendue car elle à été déjà vendue</strong>
                            {% else %}
                                <strong>Cette propriété ne peut-etre loué car elle à été déjà loué</strong>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="about-img">
                        <img src="{{ asset('assets/img/page-title.jpg') }}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="skill-area spb">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="skill-title">
                        <h2>Information  supplémentaire sur la propriété</h2>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="row">
                        <div class="col-sm-6 single-skill">
                            <dl class="row">
                                <dt class="col-sm-8">Surface</dt>
                                <dd class="col-sm-4">{{ property.surface }} m²</dd>
                            </dl>
                        </div>
                        <div class="col-sm-6 single-skill">
                            <dl class="row">
                                <dt class="col-sm-8">Pièce(s)</dt>
                                <dd class="col-sm-4">{{ property.rooms }}</dd>
                            </dl>
                        </div>
                        <div class="col-sm-6 single-skill">
                            <dl class="row">
                                <dt class="col-sm-8">Chambre(s)</dt>
                                <dd class="col-sm-4">{{ property.bedrooms }}</dd>
                            </dl>
                        </div>
                        <div class="col-sm-6 single-skill">
                            <dl class="row">
                                <dt class="col-sm-8">Etage(s)</dt>
                                <dd class="col-sm-4">{{ property.floor }}</dd>
                            </dl>
                        </div>
                        <div class="col-sm-12 single-skill">
                            <dl class="row">
                                <dt class="col-sm-4">Ville</dt>
                                <dd class="col-sm-8">{{ property.city }}</dd>
                            </dl>
                        </div>
                        <div class="col-sm-12 single-skill">
                            <dl class="row">
                                <dt class="col-sm-4">Adresse</dt>
                                <dd class="col-sm-8">{{ property.adresse }}</dd>
                            </dl>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>#}
    <div class="spb">
        <div class="brand-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-6 single-brand">
                        <div class="inner">
                            <a href="#">
                                <img src="assets/img/brand1.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-6 single-brand">
                        <div class="inner">
                            <a href="#">
                                <img src="assets/img/brand2.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-6 single-brand">
                        <div class="inner">
                            <a href="#">
                                <img src="assets/img/brand3.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-6 single-brand">
                        <div class="inner">
                            <a href="#">
                                <img src="assets/img/brand4.png" alt="">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}