src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today", message="La date d'arrivée doient être ulterieure à la date d'aujourd'hui !")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doivent être plus élogner que la date d'arrivée !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     */
    private $ad;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $confirmation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Property", inversedBy="bookings")
     */
    private $property;

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        if (empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }
        if (empty($this->amount)){
            if ($this->ad){
                $this->amount = $this->ad->getPrice() * $this->getDuration();
            }else {
                $this->amount = $this->property->getPrice() * $this->getDuration();
            }
        }
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    /**
     * @return bool
     */
    public function isBookableDays()
    {
        if ($this->ad){
            $notAvailableDays = $this->ad->getNotAvailableDays();
            $bookingDays = $this->getDays();
        }else{
            $notAvailableDays = $this->property->getNotAvailableDays();
            $bookingDays = $this->getMounth();
        }



        $formatDays = function($day){
            return $day->format('Y-m-d');
        };

        $days = array_map($formatDays, $bookingDays);
        $notAvailable = array_map($formatDays, $notAvailableDays);

        foreach ($days as $day){
            if(array_search($day, $notAvailable) !== false){
                return false;
            }
        }
        return true;
    }

    /**
     * @return array
     */
    public function getDays()
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($day){
            return new \DateTime(date('Y-m-d', $day));
        },$resultat);

        return $days;
    }

    /**
     * @return array
     */
    public function getMounth()
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        $days = array_map(function ($day){
            return new \DateTime(date('Y-m-d', $day));
        },$resultat);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?user
    {
        return $this->booker;
    }

    public function setBooker(?user $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAd(): ?ad
    {
        return $this->ad;
    }

    public function setAd(?ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getConfirmation(): ?string
    {
        return $this->confirmation;
    }

    public function setConfirmation(?string $confirmation): self
    {
        $this->confirmation = $confirmation;

        return $this;
    }

    public function getProperty(): ?property
    {
        return $this->property;
    }

    public function setProperty(?property $property): self
    {
        $this->property = $property;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTransforme\FrenchToDataTransforme;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    private $tramsformer;

    public function __construct(FrenchToDataTransforme $tramsformer)
    {
        $this->tramsformer = $tramsformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, [
                'label' => "Date d'arrivée",
                'attr' => [
                    'placeholder' => "Saisire la date d'arrivée "
                ]
            ])
            ->add('endDate', TextType::class, [
                'label' => "Date de départ",
                'attr' => [
                    'placeholder' => "Saisir la date de départ"
                ]
            ])
            ->add('comment', TextareaType::class, [
                'label' => false,
                'required' => false,
                'attr' => [
                    'placeholder' => "SI vous avez un commentaire n'hésitez pas à faire par !"
                ]
            ])
        ;
        $builder->get('startDate')->addModelTransformer($this->tramsformer);
        $builder->get('endDate')->addModelTransformer($this->tramsformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Property;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
class BookingController extends AbstractController
{
    /**
     * @Route("/booking", name="booking_index", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function index(BookingRepository $bookingRepository): Response
    {
        return $this->render('booking/index.html.twig', [
            'bookings' => $bookingRepository->findAll(),
        ]);
    }

    /**
     * @Route("/ad/{id}/booking", name="booking_new", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function new(Ad $ad, Request $request): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $booker = $this->getUser();
            $booking->setAd($ad)
                    ->setBooker($booker)
                    ->setConfirmation('En Attente...');
            if (!$booking->isBookableDays()){
                $this->addFlash('warning', "Vous ne pouvez pas faire de reservation sur cette date");
            }else{
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($booking);
                $entityManager->flush();

                return $this->redirectToRoute('booking_show',[
                    'id' => $booking->getId(),
                    'withAlert' => true
                ]);
            }

        }

        return $this->render('booking/new.html.twig', [
            'ad' => $ad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/property/{id}/booking", name="property_booking_new", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function newProperty(Property $property, Request $request): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $booker = $this->getUser();
            $booking->setProperty($property)
                ->setBooker($booker)
                ->setConfirmation('En Attente...');
            if (!$booking->isBookableDays()){
                $this->addFlash('warning', "Vous ne pouvez pas faire de reservation sur cette date");
            }else{
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($booking);
                $entityManager->flush();

                return $this->redirectToRoute('booking_show',[
                    'id' => $booking->getId(),
                    'withAlert' => true
                ]);
            }

        }

        return $this->render('booking/property/new.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/booking/{id}", name="booking_show", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function show(Booking $booking): Response
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }

}

src/Controller/admin/BookingController.php
<?php
namespace App\Controller\admin;

use App\Entity\Booking;
use App\Repository\BookingRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BookingController
 * @package App\Controller\admin
 * @Route("/admin", name="admin_")
 * @IsGranted("ROLE_ADMIN")
 */
class BookingController extends AbstractController
{

    /**
     * @Route("/booking", name="booking_index", methods={"GET","POST"})
     */
    public function index(BookingRepository $bookingRepository): Response
    {
        return $this->render('admin/booking/index.html.twig', [
            'bookings' => $bookingRepository->findAll(),
        ]);
    }


    /**
     * @Route("/booking/{id}", name="booking_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Booking $booking): Response
    {
        if ($this->isCsrfTokenValid('delete'.$booking->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($booking);
            $entityManager->flush();
        }

        return $this->redirectToRoute('booking_index');
    }

    /**
     * @Route("/booking/{id}/valide", name="booking_valide", methods={"GET","POST"})
     */
    public function valide(Booking $booking): Response
    {
        $booking->setConfirmation('Accepter');
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($booking);
        $entityManager->flush();
        return $this->redirectToRoute('booking_list');
    }
    /**
     * @Route("/booking/{id}/notvalide", name="booking_notvalide", methods={"GET","POST"})
     */
    public function notValide(Booking $booking): Response
    {
        $booking->setConfirmation('Réfuser');
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($booking);
        $entityManager->flush();
        return $this->redirectToRoute('booking_list');
    }

    /**
     * @Route("/booking/{id}", name="booking_show")
     */
    public function show(Booking $booking)
    {
        return $this->render('admin/booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }

}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('booking_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/booking/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos réservation passer et à venir {% endblock %}

{% block body %}
    <div class="page-title sp" style="background-image: url(assets/img/page-title.jpg)">
        <div class="container text-center">
            <h2>Mes réservations</h2>
            <p>Retrouvez ci-déssous toutes vos réservations passées et à venir</p>
        </div>
    </div>
    <div class="portfolio-area sp">
        <div class="container">
            {% for booking in app.user.bookings %}
                {% set ad = booking.ad %}
                {% set property = booking.property %}
                {% set validite = booking.confirmation %}
                <div class="row" style="margin-bottom: 1.5em;">
                    <div class="col-sm-4">
                        {% if ad is not null %}
                         <img src="/img/voiture/{{ ad.voiture.image }}" alt="" class="img-fluid">
                        {% else %}
                            <img src="{{ asset('assets/img/page-title.jpg') }}" alt="" class="img-fluid">
                        {% endif %}
                    </div>
                    <div class="col-sm-8">
                        <h4>
                            {% if ad == null %}
                                Propriété : {{ property.title }}
                            {% else %}
                                Voiture : {{ ad.title }}
                            {% endif %}
                        </h4>
                        <p>
                            Réservation <strong>n°{{ booking.id }}</strong><br>
                            Du {{ booking.startDate | date('d/m/Y') }} au {{ booking.endDate| date('d/m/Y') }}
                            ({{ booking.amount }} fcfa)
                        </p>
                        <p>
                            {% if validite == 'Accepter' %}
                                <h3>Accepter!</h3>
                            {% elseif validite == 'Réfuser' %}
                                <h3>Refuser!</h3>
                            {% else %}
                                <h3>En Attente...</h3>
                            {% endif %}
                        </p>
                        <a href="{{ path('booking_show', {'id': booking.id}) }}" class="btn btn-info">Plus d'informations</a>
                    </div>
                </div>
            {% else %}
                <section id="aa-error">
                    <div class="container">
                        <row>
                            <div class="col-md-12">
                                <div class="aa-error-area">
                                    <h2>Vide</h2>
                                    <p><span class="fa fa-warning"></span>Vous n'avez effectuer aucune resevation </p>
                                    <a href="{{ path('ad_index') }}">Retoure a la liste des voiture</a>
                                </div>
                            </div>
                        </row>
                    </div>
                </section>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ ad.title }} !{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap-datepicker.min.css') }}"/>
{% endblock %}

{% block body %}
    <div class="page-title sp" style="background-image: url({{ asset('assets/img/page-title.jpg') }})">
        <div class="container text-center">
            <h2>Réservation pour l'annonce : {{ ad.title }}</h2>
            <p>Vous etes sur le point de reservez le bien, dites nous tout, on s'occupe du reste!</p>
        </div>
    </div>
    <div class="container my-5">

    </div>
    <div class="contact-area sp">
        <div class="container">
            {{ form_start(form) }}
                <div class="contact-info">
                    <h2>Commencez par nous dire quelle sont les dates qui vous interessent</h2>
                    <div class="row">
                        <div class="col-sm-6">
                            {{ form_row(form.startDate) }}
                        </div>
                        <div class="col-sm-6">
                            {{ form_row(form.endDate) }}
                        </div>
                    </div>
                    <h3 class="mt-3">Montant de la reservation : <span id="amount">...</span> fcfa </h3>
                    <span id="days">0</span> jour(s) à {{ ad.price|number_format(2, '.', ' ') }}fcfa / jour
                    <h3 class="mt-4">Vous avez un commentaire ?</h3>
                    {{ form_row(form.comment) }}
                </div>
                <h2>Vous avez terminé ?</h2>
                <p>Vacances de rêve ? Mariage de rêve ? Peu importe, on est avec vous !</p>
                <button type="submit" class="btn btn-success mb-5">Je réserve !</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('assets/js/bootstrap-datepiker.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for days in ad.notAvailableDays %}
                        "{{ days.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });
            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });
        function calculateAmount(){
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if (startDate && endDate && startDate < endDate){
                const DAY_TIME = 24 * 60 * 60 * 1000;

                const intervalle = endDate.getTime() - startDate.getTime();
                const days = intervalle / DAY_TIME;
                const amount = days * {{ ad.price }};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString("fr-FR"));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{ booking.id }} !{% endblock %}

{% block body %}
    {% set ad = booking.ad %}
    {% set property = booking.property %}
    <div class="page-title sp" style="background-image: url({{ asset('assets/img/couple-heureux.jpg') }})">
        <div class="container text-center">
            <h2>Votre réservation (n°{{ booking.id }})</h2>
        </div>
    </div>
    <div class="portfolio-area sp">
        <div class="container">
            <div id="aImprimer">
                {% if app.request.query.get('withAlert') %}
                    <div class="alert alert-success">
                        <h4 class="alert-heading">Bravo !</h4>
                        <p>
                            Votre réservation auprès de
                            <strong>
                                <a href="#">LocateCar Company</a>
                            </strong>
                            pour l'annonce
                            <strong>
                                {% if ad is not null %}
                                    <a href="{{ path('ad_show', {'id': ad.id}) }}">{{ ad.title }}</a>
                                {% else %}
                                    <a href="{{ path('property_show', {'id': property.id}) }}">{{ property.title }}</a>
                                {% endif %}
                            </strong>
                            a bien été prise en compte !
                        </p>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="alert alert-ligth">
                            <h2>Détails</h2>
                            <dl class="row">
                                <dt class="col-md-4">Numéros</dt>
                                <dd class="col-md-8">{{ booking.id }}</dd>
                                <dt class="col-md-4">Date d'arrivée</dt>
                                <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                                <dt class="col-md-4">Date de départ</dt>
                                <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                                <dt class="col-md-4">Nombres de nuit</dt>
                                <dd class="col-md-8">{{ booking.duration }}</dd>
                                <dt class="col-md-4">Montant total</dt>
                                <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                                <dt class="col-md-4">Commentaire</dt>
                                <dd class="col-md-8">{{ booking.comment }}</dd>
                            </dl>
                            <hr>
                            <h2 class="alert-heading">Votre hôte</h2>
                            <div class="mb-3">
                                <dl class="row">
                                    <dt class="col-md-4">Nom societé</dt>
                                    <dd class="col-md-8">BKG TRANS Sarl</dd>
                                    <dt class="col-md-4">Contact</dt>
                                    <dd class="col-md-8">
                                        (00228) 90 38 99 14 <br>
                                        (00228) 97 05 80 20 <br>
                                        (00228) 22 54 81 90
                                    </dd>
                                    <dt class="col-md-4">Email</dt>
                                    <dd class="col-md-8">bkgtrans2@gmail.com ou <br> mathiasguede007@gamil.com</dd>
                                    <dt class="col-md-4">Adresse</dt>
                                    <dd class="col-md-8">Quartier Adidogomé</dd>
                                </dl>
                            </div>
                            <a href="" class="btn btn-primary">Plus d'info sur LocateCar Company</a>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="alert alert-ligth">
                            {% if ad is not null %}
                                <h2 class="alert-heading">Votre Voiture</h2>
                                <h4 class="my-3">
                                    <a href="{{ path('ad_show', {'id': ad.id}) }}">{{ ad.title }}</a>
                                </h4>
                                <img src="/img/voiture/{{ ad.voiture.image }}" alt="" class="img-fluid">
                                <div class="my-3">
                                    {{ ad.description | raw }}
                                </div>

                                <a href="{{ path('ad_show', {'id': ad.id}) }}" class="btn btn-primary">Plus d'information</a>
                            {% else %}
                                <h2 class="alert-heading">Votre propriété</h2>
                                <h4 class="my-3">
                                    <a href="{{ path('property_show', {'id': property.id}) }}">{{ property.title }}</a>
                                </h4>
                                <img src="{{ asset('assets/img/page-title.jpg') }}" alt="" class="img-fluid">
                                <div class="my-3">
                                    {{ property.description | raw }}
                                </div>

                                <a href="{{ path('property_show', {'id': property.id}) }}" class="btn btn-primary">Plus d'information</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <a href="#" onclick="imprimer('aImprimer')" class="btn btn-warning mb-5"><i class="la la-print"></i> Imprimez </a>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        function imprimer(divName){
            var printContents = document.getElementById(divName).innerHTML;
            var originalContents = document.body.innerHTML;
            document.body.innerHTML = printContents;
            window.print();
            document.body.innerHTML = originalContents;
        }
    </script>
{% endblock %}